New filter page
tobyakin/MySpurr-Landing-Page pull request #77
Opened 2024-10-11 20:06 UTC by Deen-Abdultawab

- Filter Implementation for Job and Talent search

2024-10-12 06:21 UTC, onyiimesi requested changes

2024-10-12 06:23 UTC, onyiimesi commented on src/services/Talents.js
> +export const getAllTalents = async (page, filters) => {
Test the filter on laptop and mobile view properly

It's not working well, also the filters that have checkbox when it's clicked, it doesn't check.

Lastly don't change anything in any of the env files again.

2024-10-12 10:38 UTC, Deen-Abdultawab commented on src/services/Talents.js
> +export const getAllTalents = async (page, filters) => {
- The page is passed to implement the pagination function
- I don't touch the env files. Will be extra cautious with that going forward.

2024-10-13 05:08 UTC, onyiimesi approved these changes

2024-10-13 05:08 UTC, merged